name: Propuesta de API
description: Propuesta de nuevo endpoint o modificación de API
title: "[API] "
labels: ["API", "PROPOSAL"]
body:
  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: Explica por qué es necesario este endpoint o cambio
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Propuesta concreta
      description: Describe claramente el endpoint o cambio propuesto
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Ejemplo técnico (JSON / request / response)
      description: Incluye ejemplo si aplica
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impacto en otros equipos
      description: Indica qué equipos deben adaptarse
    validations:
      required: true
